spring:
  application:
    name: sample-control-api
  datasource:
    url: jdbc:postgresql://localhost:5432/sample
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
